const initialValueFormulas = {
  percepcion: "1 + (Intu + Per) / 3",
  comunicacion: "1 + (Ra + Sab) / 3",
  influenciaDirecta: "1 + (Soc + Vo) / 3",
  influenciaSutil: "1 + (Ra + Soc) / 3",
  autocontrol: "1 + (Vo * 2) / 3",
  conocGenerales: "1 + (Sab * 2) / 3",
  conocMagicos: "1 + (Intu + Sab) / 3",
  conocTecnicos: "1 + (Ra + Sab) / 3",
  atletismoGim: "1 + (Ag * 2) / 3",
  atletismoPot: "1 + (Fu * 2) / 3",
  atletismoRes: "1 + (Re * 2) / 3",
  subterfugioDef: "1 + (Ag + Intu) / 3",
  oficiosFis: "1 + (Fu + Sab) / 3",
  oficiosTec: "1 + (Intu + Sab) / 3",
  comercio: "1 + (Intu + Soc) / 3",
  arteActivo: "1 + (Soc + Vo) / 3",
  artePasivo: "1 + (Ra + Intu) / 3",
  unique: {
    tacticasCbt: "1 + (Fu + Sab) / 3",
    florituras: "1 + (Ag + Intu) / 3",
    primerosAux: "1 + (Intu + Sab) / 3",
    desenvaineVeloz: "1 + (Ag + Fu) / 3",
    ataqueSilencioso: "1 + (Ag + Intu) / 3",
    desarmar: "3",
    abrirCerraduras: "1 + (Ra + Per) / 3",
    hurgarBolsillos: "1 + (Intu + Per) / 3",
    armarTrampas: "1 + (Ra + Intu) / 3",
    espeleologia: "1 + (Intu + Sab) / 3",
    supervivencia: "1 + (Re + Vo) / 3",
    orientacionCeleste: "1 + (Sab + Per) / 3",
    orientacionClimatica: "1 + (Intu + Per) / 3",
    montar: "1 + (Re + Intu) / 3",
    domesticar: "1 + (Fu + Vo) / 3",
    cazar: "1 + (Fu + Ra) / 3",
    contactos: "1 + (Soc * 2) / 3",
    mezclarse: "1 + (Soc + Per) / 3",
    busquedaUrbana: "1 + (Intu + Soc) / 3",
  },
};

enum PlayerSkills {
  RASTREO = "rastreo",
  REGISTRAR = "registrar",
  DETECTAR_SUSTANCIAS = "detectar sustancias",
  LENGUAS_ANTIGUAS = "lenguas antiguas",
  SENAS_Y_LEER_LABIOS = "señas y leer labios",
  LIDERAZGO = "liderazgo",
  INTERROGACION = "interrogación",
  SEDUCCIÓN = "seducción",
  INTIMIDAR = "intimidar",
  DIPLOMACIA = "diplomacia",
  ORATORIA = "oratoria",
  SOBORNO = "soborno",
  OFUSCAR = "ofuscar",
  MEDITACIÓN = "meditación",
  SUPERAR_ATURDIMIENTO = "superar aturdimiento",
  IGNORAR_DOLOR = "ignorar dolor",
  RESISTIR_PERSUACION = "resistir persuasión",
  FLORA = "flora",
  FAUNA = "fauna",
  HISTORIA = "historia",
  HERÁLDICA = "heráldica",
  ARTEFACTOS = "artefactos",
  HECHIZOS_Y_RUNAS = "hechizos y runas",
  CRIATURAS_MAGICAS = "criaturas mágicas",
  ETIQUETA = "etiqueta",
  LEYES = "leyes",
  ANATOMÍA = "anatomía",
  MECÁNICA = "mecánica",
  FORTIFICACIONES = "fortificaciones",
  FISICA = "física",
  NUDOS = "nudos",
  HIERBAS = "hierbas",
  ASTRONOMÍA = "astronomía",
  VENENOS = "venenos",
  LEYES_COMERCIALES = "leyes comerciales",
  TACTICAS_DE_COMBATE = "tácticas de combate",
  MALABARES_Y_FLORITURAS = "malabares y florituras",
  PRIMEROS_AUXILIOS = "primeros auxilios",
  DESENVAINAR_VELOZ = "desenvaine veloz",
  ATAQUE_SILENCIOSO = "ataque silencioso",
  DESARMAR = "desarmar (maniobra)",
  ACROBACIAS = "acrobacias",
  CONTORSIONISMO = "contorsionismo",
  CAER_CAIDA = "caer/caida/equilibrio",
  LEVANTAR_PESOS = "levantar pesos",
  SALTAR_SALTOS = "saltar/saltos",
  ESPRINTAR = "esprintar/pique",
  NADAR = "nadar",
  CARRERA_DE_LARGA_DISTANCIA = "carrera de larga distancia",
  TREPAR_Y_ESCALAR = "trepar y escalar",
  ABRIR_CERRADURAS = "abrir cerraduras",
  HURGAR_BOLSILLOS = "hurgar bolsillos",
  ARMAR_TRAMPAS = "armar trampas",
  SIGILO = "sigilo",
  ESCONDERSE = "esconderse",
  CAMUFLAR = "camuflar",
  DISFRAZ = "disfraz",
  AGILIDAD_MANUAL = "agilidad manual (prestidigitación)",
  ESPELEOLOGIA = "espeleología",
  SUPERVIVENCIA = "supervivencia",
  ORIENTACION_CELESTE = "orientacion celeste",
  ORIENTACION_CLIMATICA = "orientacion climática",
  MONTAR = "montar",
  ADIESTRAR_DOMESTICAR = "adiestrar/domesticar",
  CAZAR = "cazar",
  CONTACTOS = "contactos",
  MEZCLARSE = "mezclarse",
  INSTINTO_CALLEJERO = "instinto callejero",
  BÚSQUEDA_URBANA = "búsqueda urbana",
  TALABARTERIA = "talabartería",
  TALLAR_MADERA = "tallar madera",
  ALBAÑILERIA = "albañilería",
  HERRERIA = "herrería",
  ORFEBRERIA = "orfebrería",
  MINERIA = "minería",
  CALIGRAFIA_ESCRIBA = "caligrafía/escriba",
  FALSIFICAR_DOCUMENTOS = "falsificar documentos",
  NAVEGACION = "navegación",
  CARTOGRAFIA = "cartografía",
  TASACION = "tasación",
  REGATEO = "regateo",
  MENDIGAR = "mendigar",
  APOSTAR = "apostar",
  ACTUACION_Y_MIMICA = "actuación y mímica",
  TOCAR_INSTRUMENTO = "tocar instrumento",
  CANTAR = "cantar",
  IMITAR_SONIDOS = "imitar sonidos",
  PINTURA = "pintura",
  ESCULTURA = "escultura",
  POESIA = "poesía",
}

type ValidPlayerSkills = (typeof PlayerSkills)[keyof typeof PlayerSkills];

type Skill = {
  formulaName: ValidPlayerSkills;
  name: string[];
  initialValFormula: string;
};

const allSkills: Skill[] = [
  {
    formulaName: PlayerSkills.RASTREO,
    name: ["Rastreo", "Tracking"],
    initialValFormula: initialValueFormulas.percepcion,
  },
  {
    formulaName: PlayerSkills.REGISTRAR,
    name: ["Registrar", "Registering"],
    initialValFormula: initialValueFormulas.percepcion,
  },
  {
    formulaName: PlayerSkills.DETECTAR_SUSTANCIAS,
    name: ["Detectar sustancias", "Detect substances"],
    initialValFormula: initialValueFormulas.percepcion,
  },
  {
    formulaName: PlayerSkills.LENGUAS_ANTIGUAS,
    name: ["Lenguas antiguas", "Ancient languages"],
    initialValFormula: initialValueFormulas.comunicacion,
  },
  {
    formulaName: PlayerSkills.SENAS_Y_LEER_LABIOS,
    name: ["Señas y leer labios", "Sign language and lip reading"],
    initialValFormula: initialValueFormulas.comunicacion,
  },
  {
    formulaName: PlayerSkills.LIDERAZGO,
    name: ["Liderazgo", "Leadership"],
    initialValFormula: initialValueFormulas.influenciaDirecta,
  },
  {
    formulaName: PlayerSkills.INTERROGACION,
    name: ["Interrogación", "Interrogation"],
    initialValFormula: initialValueFormulas.influenciaDirecta,
  },
  {
    formulaName: PlayerSkills.SEDUCCIÓN,
    name: ["Seducción", "Seduction"],
    initialValFormula: initialValueFormulas.influenciaDirecta,
  },
  {
    formulaName: PlayerSkills.INTIMIDAR,
    name: ["Intimidar", "Intimidation"],
    initialValFormula: initialValueFormulas.influenciaDirecta,
  },
  {
    formulaName: PlayerSkills.DIPLOMACIA,
    name: ["Diplomacia", "Diplomacy"],
    initialValFormula: initialValueFormulas.influenciaSutil,
  },
  {
    formulaName: PlayerSkills.ORATORIA,
    name: ["Oratoria", "Public speaking"],
    initialValFormula: initialValueFormulas.influenciaSutil,
  },
  {
    formulaName: PlayerSkills.SOBORNO,
    name: ["Soborno", "Bribery"],
    initialValFormula: initialValueFormulas.influenciaSutil,
  },
  {
    formulaName: PlayerSkills.OFUSCAR,
    name: ["Ofuscar", "Obfuscation"],
    initialValFormula: initialValueFormulas.influenciaSutil,
  },
  {
    formulaName: PlayerSkills.MEDITACIÓN,
    name: ["Meditación", "Meditate"],
    initialValFormula: initialValueFormulas.autocontrol,
  },
  {
    formulaName: PlayerSkills.SUPERAR_ATURDIMIENTO,
    name: ["Superar aturdimiento", "Overcoming dizziness"],
    initialValFormula: initialValueFormulas.autocontrol,
  },
  {
    formulaName: PlayerSkills.IGNORAR_DOLOR,
    name: ["Ignorar dolor", "Ignore pain"],
    initialValFormula: initialValueFormulas.autocontrol,
  },
  {
    formulaName: PlayerSkills.RESISTIR_PERSUACION,
    name: ["Resistir persuasión", "Resisting persuasion"],
    initialValFormula: initialValueFormulas.autocontrol,
  },
  {
    formulaName: PlayerSkills.FLORA,
    name: ["Flora", "Flora"],
    initialValFormula: initialValueFormulas.conocGenerales,
  },
  {
    formulaName: PlayerSkills.FAUNA,
    name: ["Fauna", "Fauna"],
    initialValFormula: initialValueFormulas.conocGenerales,
  },
  {
    formulaName: PlayerSkills.HISTORIA,
    name: ["Historia", "History"],
    initialValFormula: initialValueFormulas.conocGenerales,
  },
  {
    formulaName: PlayerSkills.HERÁLDICA,
    name: ["Heráldica", "Heraldry"],
    initialValFormula: initialValueFormulas.conocGenerales,
  },
  {
    formulaName: PlayerSkills.ARTEFACTOS,
    name: ["Artefactos", "Artifacts"],
    initialValFormula: initialValueFormulas.conocMagicos,
  },
  {
    formulaName: PlayerSkills.HECHIZOS_Y_RUNAS,
    name: ["Hechizos y runas", "Spells and Runes"],
    initialValFormula: initialValueFormulas.conocMagicos,
  },
  {
    formulaName: PlayerSkills.CRIATURAS_MAGICAS,
    name: ["Criaturas mágicas", "Magical Creatures"],
    initialValFormula: initialValueFormulas.conocMagicos,
  },
  {
    formulaName: PlayerSkills.ETIQUETA,
    name: ["Etiqueta", "Etiquette"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.LEYES,
    name: ["Leyes", "Laws"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.ANATOMÍA,
    name: ["Anatomía", "Anatomy"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.MECÁNICA,
    name: ["Mecánica", "Mechanics"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.FORTIFICACIONES,
    name: ["Fortificaciones", "Fortifications"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.FISICA,
    name: ["Física", "Physics"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.NUDOS,
    name: ["Nudos", "Knots"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.HIERBAS,
    name: ["Hierbas", "Herbs"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.ASTRONOMÍA,
    name: ["Astronomía", "Astronomy"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.VENENOS,
    name: ["Venenos", "Poisons"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.LEYES_COMERCIALES,
    name: ["Leyes comerciales", "Commercial laws"],
    initialValFormula: initialValueFormulas.conocTecnicos,
  },
  {
    formulaName: PlayerSkills.TACTICAS_DE_COMBATE,
    name: ["Tácticas de combate", "Combat Tactics"],
    initialValFormula: initialValueFormulas.unique.tacticasCbt,
  },
  {
    formulaName: PlayerSkills.MALABARES_Y_FLORITURAS,
    name: ["Malabares y florituras", "Juggling and flourishes"],
    initialValFormula: initialValueFormulas.unique.florituras,
  },
  {
    formulaName: PlayerSkills.PRIMEROS_AUXILIOS,
    name: ["Primeros auxilios", "First Aid"],
    initialValFormula: initialValueFormulas.unique.primerosAux,
  },
  {
    formulaName: PlayerSkills.DESENVAINAR_VELOZ,
    name: ["Desenvaine veloz", "Quick draw"],
    initialValFormula: initialValueFormulas.unique.desenvaineVeloz,
  },
  {
    formulaName: PlayerSkills.ATAQUE_SILENCIOSO,
    name: ["Ataque silencioso", "Silent Attack"],
    initialValFormula: initialValueFormulas.unique.ataqueSilencioso,
  },
  {
    formulaName: PlayerSkills.DESARMAR,
    name: ["Desarmar (maniobra)", "Disarm"],
    initialValFormula: initialValueFormulas.unique.desarmar,
  },
  {
    formulaName: PlayerSkills.ACROBACIAS,
    name: ["Acrobacias", "Acrobatics"],
    initialValFormula: initialValueFormulas.atletismoGim,
  },
  {
    formulaName: PlayerSkills.CONTORSIONISMO,
    name: ["Contorsionismo", "Contortionism"],
    initialValFormula: initialValueFormulas.atletismoGim,
  },
  {
    formulaName: PlayerSkills.CAER_CAIDA,
    name: ["Caida/equilibrio", "Falling/Balance"],
    initialValFormula: initialValueFormulas.atletismoGim,
  },
  {
    formulaName: PlayerSkills.LEVANTAR_PESOS,
    name: ["Levantar pesos", "Weightlifting"],
    initialValFormula: initialValueFormulas.atletismoPot,
  },
  {
    formulaName: PlayerSkills.SALTAR_SALTOS,
    name: ["Saltar/saltos", "Jumping/Jumps"],
    initialValFormula: initialValueFormulas.atletismoPot,
  },
  {
    formulaName: PlayerSkills.ESPRINTAR,
    name: ["Esprintar/pique", "Sprinting"],
    initialValFormula: initialValueFormulas.atletismoPot,
  },
  {
    formulaName: PlayerSkills.NADAR,
    name: ["†Nadar", "†Swimming"],
    initialValFormula: initialValueFormulas.atletismoRes,
  },
  {
    formulaName: PlayerSkills.CARRERA_DE_LARGA_DISTANCIA,
    name: ["Carrera de larga distancia", "Long-distance running"],
    initialValFormula: initialValueFormulas.atletismoRes,
  },
  {
    formulaName: PlayerSkills.TREPAR_Y_ESCALAR,
    name: ["Trepar y escalar", "Climbing and scaling"],
    initialValFormula: initialValueFormulas.atletismoRes,
  },
  {
    formulaName: PlayerSkills.ABRIR_CERRADURAS,
    name: ["Abrir cerraduras", "Lockpicking"],
    initialValFormula: initialValueFormulas.unique.abrirCerraduras,
  },
  {
    formulaName: PlayerSkills.HURGAR_BOLSILLOS,
    name: ["Hurgar bolsillos", "Pickpocket"],
    initialValFormula: initialValueFormulas.unique.hurgarBolsillos,
  },
  {
    formulaName: PlayerSkills.ARMAR_TRAMPAS,
    name: ["Armar trampas", "Setting traps"],
    initialValFormula: initialValueFormulas.unique.armarTrampas,
  },
  {
    formulaName: PlayerSkills.SIGILO,
    name: ["Sigilo", "Stealth"],
    initialValFormula: initialValueFormulas.subterfugioDef,
  },
  {
    formulaName: PlayerSkills.ESCONDERSE,
    name: ["Esconderse", "Hiding"],
    initialValFormula: initialValueFormulas.subterfugioDef,
  },
  {
    formulaName: PlayerSkills.CAMUFLAR,
    name: ["Camuflar", "Camouflage"],
    initialValFormula: initialValueFormulas.subterfugioDef,
  },
  {
    formulaName: PlayerSkills.DISFRAZ,
    name: ["Disfraz", "Disguise"],
    initialValFormula: initialValueFormulas.subterfugioDef,
  },
  {
    formulaName: PlayerSkills.AGILIDAD_MANUAL,
    name: ["Agilidad manual (prestidigitación)", "Sleight of hand"],
    initialValFormula: initialValueFormulas.subterfugioDef,
  },
  {
    formulaName: PlayerSkills.ESPELEOLOGIA,
    name: ["Espeleología", "Spelunky"],
    initialValFormula: initialValueFormulas.unique.espeleologia,
  },
  {
    formulaName: PlayerSkills.SUPERVIVENCIA,
    name: ["Supervivencia", "Survival"],
    initialValFormula: initialValueFormulas.unique.supervivencia,
  },
  {
    formulaName: PlayerSkills.ORIENTACION_CELESTE,
    name: ["Orientacion celeste", "Celestial navigation"],
    initialValFormula: initialValueFormulas.unique.orientacionCeleste,
  },
  {
    formulaName: PlayerSkills.ORIENTACION_CLIMATICA,
    name: ["Orientacion climática", "Weather forecasting"],
    initialValFormula: initialValueFormulas.unique.orientacionClimatica,
  },
  {
    formulaName: PlayerSkills.MONTAR,
    name: ["†Montar", "†Riding"],
    initialValFormula: initialValueFormulas.unique.montar,
  },
  {
    formulaName: PlayerSkills.ADIESTRAR_DOMESTICAR,
    name: ["Adiestrar/domesticar", "Training/Taming"],
    initialValFormula: initialValueFormulas.unique.domesticar,
  },
  {
    formulaName: PlayerSkills.CAZAR,
    name: ["Cazar", "Hunting"],
    initialValFormula: initialValueFormulas.unique.cazar,
  },
  {
    formulaName: PlayerSkills.CONTACTOS,
    name: ["Contactos", "Connections"],
    initialValFormula: initialValueFormulas.unique.contactos,
  },
  {
    formulaName: PlayerSkills.MEZCLARSE,
    name: ["Mezclarse", "Blending in"],
    initialValFormula: initialValueFormulas.unique.mezclarse,
  },
  {
    formulaName: PlayerSkills.BÚSQUEDA_URBANA,
    name: [
      "Búsqueda urbana / Instinto callejero",
      "Urban scouting / Street smarts",
    ],
    initialValFormula: initialValueFormulas.unique.busquedaUrbana,
  },
  {
    formulaName: PlayerSkills.TALABARTERIA,
    name: ["Talabartería", "Leatherworking"],
    initialValFormula: initialValueFormulas.oficiosFis,
  },
  {
    formulaName: PlayerSkills.TALLAR_MADERA,
    name: ["Tallar madera", "Wood carving"],
    initialValFormula: initialValueFormulas.oficiosFis,
  },
  {
    formulaName: PlayerSkills.ALBAÑILERIA,
    name: ["Albañilería", "Masonry"],
    initialValFormula: initialValueFormulas.oficiosFis,
  },
  {
    formulaName: PlayerSkills.HERRERIA,
    name: ["Herrería", "Blacksmithing"],
    initialValFormula: initialValueFormulas.oficiosFis,
  },
  {
    formulaName: PlayerSkills.ORFEBRERIA,
    name: ["Orfebrería", "Jewelry making"],
    initialValFormula: initialValueFormulas.oficiosFis,
  },
  {
    formulaName: PlayerSkills.MINERIA,
    name: ["Minería", "Mining"],
    initialValFormula: initialValueFormulas.oficiosFis,
  },
  {
    formulaName: PlayerSkills.CALIGRAFIA_ESCRIBA,
    name: ["Caligrafía/escriba", "Calligraphy/Scribing"],
    initialValFormula: initialValueFormulas.oficiosTec,
  },
  {
    formulaName: PlayerSkills.FALSIFICAR_DOCUMENTOS,
    name: ["Falsificar documentos", "Forging documents"],
    initialValFormula: initialValueFormulas.oficiosTec,
  },
  {
    formulaName: PlayerSkills.NAVEGACION,
    name: ["Navegación", "Navigation"],
    initialValFormula: initialValueFormulas.oficiosTec,
  },
  {
    formulaName: PlayerSkills.CARTOGRAFIA,
    name: ["Cartografía", "Cartography"],
    initialValFormula: initialValueFormulas.oficiosTec,
  },
  {
    formulaName: PlayerSkills.TASACION,
    name: ["Tasación", "Object Appraisal"],
    initialValFormula: initialValueFormulas.comercio,
  },
  {
    formulaName: PlayerSkills.REGATEO,
    name: ["Regateo", "Haggling"],
    initialValFormula: initialValueFormulas.comercio,
  },
  {
    formulaName: PlayerSkills.MENDIGAR,
    name: ["Mendigar", "Begging"],
    initialValFormula: initialValueFormulas.comercio,
  },
  {
    formulaName: PlayerSkills.APOSTAR,
    name: ["Apostar", "Gambling"],
    initialValFormula: initialValueFormulas.comercio,
  },
  {
    formulaName: PlayerSkills.ACTUACION_Y_MIMICA,
    name: ["Actuación y mímica", "Acting and mime"],
    initialValFormula: initialValueFormulas.arteActivo,
  },
  {
    formulaName: PlayerSkills.TOCAR_INSTRUMENTO,
    name: ["Tocar instrumento", "Playing an instrument"],
    initialValFormula: initialValueFormulas.arteActivo,
  },
  {
    formulaName: PlayerSkills.CANTAR,
    name: ["Cantar", "Singing"],
    initialValFormula: initialValueFormulas.arteActivo,
  },
  {
    formulaName: PlayerSkills.IMITAR_SONIDOS,
    name: ["Imitar sonidos", "Imitating sounds"],
    initialValFormula: initialValueFormulas.arteActivo,
  },
  {
    formulaName: PlayerSkills.PINTURA,
    name: ["Pintura", "Painting"],
    initialValFormula: initialValueFormulas.artePasivo,
  },
  {
    formulaName: PlayerSkills.ESCULTURA,
    name: ["Escultura", "Sculpture"],
    initialValFormula: initialValueFormulas.artePasivo,
  },
  {
    formulaName: PlayerSkills.POESIA,
    name: ["Poesía", "Poetry"],
    initialValFormula: initialValueFormulas.artePasivo,
  },
];
